# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Format
      run: dotnet format --verify-no-changes

        
    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
        
    - name: Unit Tests Report
      uses: dorny/test-reporter@v1
      with:
        name: unitTests                  
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/finance-tracker-api:${{ github.sha }} .

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/finance-tracker-api:${{ github.sha }}
